import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TABLE product_images (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      position int NOT NULL,
      url text NOT NULL,
      product_id int 
    )
    `);

  await knex.raw(`ALTER TABLE product_images ADD CONSTRAINT fk_product_images_product_id FOREIGN KEY (product_id) REFERENCES products`)
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE product_images
  `);
}

