import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TABLE categories (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title text NOT NULL,
      image text
    );
    `)

  await knex.raw(`ALTER TABLE products ADD COLUMN "categoryId" int REFERENCES categories(id)`)
}


export async function down(knex: Knex): Promise<void> {
  await knex.raw(`
    ALTER TABLE products
      DROP COLUMN categoryId;
    `);
  await knex.raw(`DROP TABLE categories`);
}

