import { Knex } from "knex";


export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE products (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title text NOT NULL,
      description text NOT NULL,
      characteristics text NOT NULL,
      points text NOT NULL,
      price integer
    )
  `);
}


export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE products
  `);
}

