import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TABLE sub_categories (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title text NOT NULL,
      image text,
      "categoryId" int 
    );
    `);

  await knex.raw(
    `ALTER TABLE sub_categories ADD CONSTRAINT fk_sub_categories_category_id FOREIGN KEY ("categoryId") REFERENCES categories`,
  );

  await knex.raw(
    `ALTER TABLE products ADD COLUMN "subCategoryId" int REFERENCES sub_categories(id)`,
  );
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`
    ALTER TABLE products
      DROP COLUMN "subCategoryId";
    `);
  await knex.raw(`DROP TABLE sub_categories`);
}
